### ISSUE TITLE
Na czwartek 04.04

### ISSUE THREAD

**Issue by KD377** [KD377/AutoStudentReportLLMs#1]
- [x] Change the LLM model for GROQ or GPT 3.5 Turbo (If we decide to pay)
- [x] Using the prompt format from MS Teams generate queries for chromaDB in JSON format
- [ ] Implement logic for RAG. Using the generated queries and the context format grade the task.
- [x] Response should be in JSON as follows [{points: 5, description: "1-2 sentences why so "}]
- [x] Create a report file with gradings in order to provide the context for LLM to grade Conclusions section as it should be related to the outcome of the experiments

**Comment by hare32** [comment]
**GROQ has been successfully added to our project!**
